#!/usr/bin/env bash
# post-write-hook.sh — PostToolUse hook for Write/Edit operations.
# Triggers docs registry refresh on STATE.json writes and appends to
# CHANGES.md for writes to numbered folders.
set -uo pipefail

# Hook input arrives as JSON on stdin (Claude Code contract). There is no
# TOOL_INPUT_FILE_PATH env var — parse the path from .tool_input.file_path.
INPUT=$(cat 2>/dev/null || true)
FILE_PATH=$(printf '%s' "$INPUT" | python3 -c "import sys,json
try: d=json.load(sys.stdin)
except Exception: d={}
print((d.get('tool_input') or {}).get('file_path','') or '')" 2>/dev/null || true)
[ -z "$FILE_PATH" ] && exit 0

# Two distinct roots: TOOLS_DIR is where these scripts live (the workflow repo);
# PROJECT_ROOT is the build's cwd (where .rapid/ and the numbered folders are).
# Build artifacts (CHANGES.md, STATE.json) belong to the project, not the repo.
TOOLS_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$PWD"

# Only act inside an active build
[ -f "$PROJECT_ROOT/.rapid/STATE.json" ] || exit 0

# STATE.json write (phase change) → cross-system refresh so docs/dashboard/cost
# stay current with the build (the deterministic half of integration). Deck pages
# are regenerated by /docs at gates (an LLM step, not hookable).
if [[ "$FILE_PATH" == *".rapid/STATE.json"* ]]; then
  bash "$TOOLS_DIR/build-docs-registry.sh" 2>/dev/null || true
  # refresh the cost page if the project has one
  [ -f "$PROJECT_ROOT/docs/cost.html" ] && bash "$TOOLS_DIR/cost-summary.sh" --html >/dev/null 2>&1 || true
  exit 0
fi

# ── Mechanical observe logging ───────────────────────────────────────────────
# Every Write/Edit also emits a WRITE event to the role's observe stream with a
# monotonic seq from .rapid/observe/seq.txt (pre-increment) — so the timeline
# populates whether or not the agent remembered to log it ("mechanical, not
# voluntary"). RAPID_ROLE is exported per terminal at P6a; default orchestrator.
# Best-effort: PostToolUse hooks fire ~serially per terminal, so the read-inc-write
# of seq.txt is portable (no flock needed on macOS) and collision-safe enough.
OBS_DIR="$PROJECT_ROOT/.rapid/observe"
if mkdir -p "$OBS_DIR" 2>/dev/null; then
  ROLE="${RAPID_ROLE:-orchestrator}"; SEQ_FILE="$OBS_DIR/seq.txt"
  _S=$(cat "$SEQ_FILE" 2>/dev/null || echo 0); SEQ=$(( _S + 1 )); printf '%s' "$SEQ" > "$SEQ_FILE"
  _REL=$(python3 -c "import os;print(os.path.relpath('$FILE_PATH','$PROJECT_ROOT'))" 2>/dev/null || echo "$FILE_PATH")
  _PH=$(python3 -c "import json;print('P'+str(json.load(open('$PROJECT_ROOT/.rapid/STATE.json')).get('phase','?')))" 2>/dev/null || echo "—")
  python3 - "$OBS_DIR/$ROLE.jsonl" "$SEQ" "$ROLE" "$_REL" "$_PH" <<'PY' 2>/dev/null || true
import json, sys, datetime
f, seq, role, rel, ph = sys.argv[1:6]
open(f, "a").write(json.dumps({"t": datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S.000Z"),
    "seq": int(seq), "agent": role, "role": role, "event": "WRITE", "detail": rel, "phase": ph, "task": ""}) + "\n")
PY
fi

# Numbered folder, decisions/, panels/, tests/ → append to CHANGES.md
if [[ "$FILE_PATH" =~ [0-9]{2}-[^/]+ ]] || \
   [[ "$FILE_PATH" == *"decisions/"* ]] || \
   [[ "$FILE_PATH" == *"panels/"* ]] || \
   [[ "$FILE_PATH" == *"tests/"* ]]; then

  CHANGES_FILE="$PROJECT_ROOT/CHANGES.md"
  TIMESTAMP=$(date -u +%Y-%m-%dT%H:%MZ)
  REL_PATH=$(python3 -c "import os; print(os.path.relpath('$FILE_PATH', '$PROJECT_ROOT'))" 2>/dev/null || echo "$FILE_PATH")

  # Extract phase from STATE.json if it exists
  PHASE="—"
  if [ -f "$PROJECT_ROOT/.rapid/STATE.json" ]; then
    PHASE=$(python3 -c "import json; print('P'+str(json.load(open('$PROJECT_ROOT/.rapid/STATE.json')).get('phase','?')))" 2>/dev/null || echo "—")
  fi

  # Create CHANGES.md with header if it doesn't exist
  if [ ! -f "$CHANGES_FILE" ]; then
    printf '| Date | Phase | File | Change |\n|------|-------|------|--------|\n' > "$CHANGES_FILE"
  fi

  printf '| %s | %s | %s | Write/Edit |\n' "$TIMESTAMP" "$PHASE" "$REL_PATH" >> "$CHANGES_FILE"
fi

exit 0
