#!/usr/bin/env bash
# selftest.sh — the rapid-workflow self-test suite.
#
# 38 checks across 6 dimensions, derived from the rapid-selftest audit workflow:
#   1. Unified header / navigation consistency
#   2. Visual theme consistency (dark "Constellation" palette)
#   3. Observability — dynamically built + hooked up
#   4. Evals + Test Theater — dynamically built + hooked up
#   5. Documentation / Atlas coherence (Atlas in sync with SKILL.md)
#   6. The "dynamically built" claim is real (generators derive, not copy)
#
# Static/CLI checks run against the repo. A few exercise the live demo fixture at
# /tmp/rapid-demo-shop (generated by /test-theater + /observe); those SKIP if it's
# absent. Run from anywhere: tools/selftest.sh  [--only <dimension-substr>]
set -uo pipefail
cd "$(dirname "$0")/.." || { echo "selftest: cannot find repo root"; exit 2; }
DEMO="${RAPID_DEMO:-/tmp/rapid-demo-shop}"
ONLY="${2:-}"; [ "${1:-}" = "--only" ] && ONLY="${2:-}"

PASS=0; FAIL=0; SKIP=0; declare -a FAILED=()
C0="\033[0m"; CG="\033[32m"; CR="\033[31m"; CY="\033[33m"; CB="\033[1m"
ok(){ PASS=$((PASS+1)); printf "  ${CG}✓${C0} %s\n" "$1"; }
no(){ FAIL=$((FAIL+1)); FAILED+=("$1"); printf "  ${CR}✗${C0} %s\n" "$1${2:+  — $2}"; }
sk(){ SKIP=$((SKIP+1)); printf "  ${CY}∼${C0} %s (skip: %s)\n" "$1" "$2"; }
grp(){ [ -n "$ONLY" ] && [[ "$1" != *"$ONLY"* ]] && SKIPGRP=1 || SKIPGRP=0; [ "$SKIPGRP" = 0 ] && printf "\n${CB}%s${C0}\n" "$1"; }
# run a check only if its group is active
on(){ [ "${SKIPGRP:-0}" = 0 ]; }

# ───────────────────────────────────────────────────────────── 1. NAV
grp "1 · Unified header / navigation"
if on; then
  # 01 both nav implementations list the same core destinations
  core_ok(){ for L in "Skills Atlas" "Workflow" "Architecture" "Test Suite" "Documentation"; do grep -q "$L" "$1" || return 1; done; grep -qiE 'Observatory' "$1" && grep -qiE 'How.{0,12}it.{0,12}works' "$1"; }
  core_ok docs/rapid-nav.js && core_ok tools/atlas-skills-gen.py && ok "nav_destination_parity" || no "nav_destination_parity" "nav sources diverge"
  # 02 flat surfaces include rapid-nav.js
  m=""; for f in home observatory testsuite documentation architecture workflow cost eval; do grep -q 'rapid-nav.js' "docs/$f.html" || m="$m $f"; done
  [ -z "$m" ] && ok "flat_surfaces_include_nav" || no "flat_surfaces_include_nav" "missing:$m"
  # 03 nav targets exist
  m=""; for t in workflow architecture observatory testsuite documentation home how-it-works; do [ -f "docs/$t.html" ] || m="$m $t"; done; [ -f docs/atlas-v2/index.html ] || m="$m atlas-v2/index"
  [ -z "$m" ] && ok "nav_targets_exist" || no "nav_targets_exist" "404:$m"
  # 04 atlas hub links all pages (no orphans)
  orph=$(ls docs/atlas-v2/*.html | grep -v '/index.html$' | while read -r p; do f=$(basename "$p"); grep -q "href=\"$f\"" docs/atlas-v2/index.html || echo "$f"; done)
  [ -z "$orph" ] && ok "atlas_hub_no_orphans" || no "atlas_hub_no_orphans" "orphans: $(echo $orph)"
  # 05 no dangling local links inside atlas pages
  dang=$(for p in docs/atlas-v2/*.html; do grep -oE 'href="[^"]+"' "$p" | sed -E 's/href="//;s/"$//' | grep -vE '^(https?:|mailto:|#)' | sed 's/#.*//' | while read -r h; do [ -n "$h" ] && [ ! -e "docs/atlas-v2/$h" ] && echo "$p->$h"; done; done)
  [ -z "$dang" ] && ok "atlas_no_dangling_links" || no "atlas_no_dangling_links" "$(echo $dang | head -c80)"
  # 06 how-it-works has a way back
  grep -qE 'rapid-nav.js|href="(\.\./)?home.html"|href="(\.\./)?index.html"' docs/how-it-works.html && ok "how_it_works_header_gap" || no "how_it_works_header_gap" "no header / no way back"
  # 07 sidebar preserves full relative href
  grep -q 'out.push(\[clean' docs/sidebar.js && grep -q "split('#')\[0\]" docs/sidebar.js && ok "sidebar_preserves_relative_href" || no "sidebar_preserves_relative_href" "collapses to slug"
fi

# ───────────────────────────────────────────────────────────── 2. THEME
grp "2 · Visual theme consistency"
if on; then
  PAGES="home observatory testsuite documentation architecture workflow cost eval ecc-analysis token-trends"
  # 10 off-theme detector (page has the dark token somewhere)
  off=""; for f in $PAGES; do grep -q '0D1117' "docs/$f.html" || off="$off $f"; done
  [ -z "$off" ] && ok "off_theme_page_detector" || no "off_theme_page_detector" "off-theme:$off"
  # 11 effective --bg (last declared) is dark
  light=""; for f in $PAGES; do v=$(grep -oiE -- '--bg:[[:space:]]*#?[0-9a-f]{3,6}' "docs/$f.html" | tail -1); echo "$v" | grep -qi '0D1117' || light="$light $f"; done
  [ -z "$light" ] && ok "effective_bg_is_dark" || no "effective_bg_is_dark" "not-dark:$light"
  # 12 re-themed app pages carry the dark body lock
  m=""; for f in observatory testsuite architecture workflow; do grep -q 'background:#0D1117 !important' "docs/$f.html" || m="$m $f"; done
  [ -z "$m" ] && ok "dark_body_lock_on_rethemed_pages" || no "dark_body_lock_on_rethemed_pages" "no-lock:$m"
  # 13 shared nav idiom (incl. the briefs)
  m=""; for f in $PAGES; do grep -q 'rapid-nav.js' "docs/$f.html" || m="$m $f"; done
  [ -z "$m" ] && ok "shared_nav_idiom" || no "shared_nav_idiom" "no-nav:$m"
  # 14 token-trends canonical token vocabulary
  grep -qE -- '--text-muted|--text-dim|--border-light' docs/token-trends.html && ok "canonical_token_vocabulary" || no "canonical_token_vocabulary" "non-standard token names"
  # 15 tag balance across docs/*.html
  bad=$(python3 - <<'PY'
import re,glob
out=[]
for f in glob.glob('docs/*.html'):
    s=open(f).read(); s=re.sub(r'<style.*?</style>','',s,flags=re.S); s=re.sub(r'<script.*?</script>','',s,flags=re.S)
    for t in ('div','section','table'):
        o=len(re.findall(r'<'+t+r'[\s>]',s)); c=len(re.findall(r'</'+t+'>',s))
        if o!=c: out.append(f"{f}:{t} {o}/{c}")
print('\n'.join(out))
PY
)
  [ -z "$bad" ] && ok "html_tag_balance" || no "html_tag_balance" "$(echo $bad | head -c80)"
fi

# ───────────────────────────────────────────────────────────── 3. OBSERVABILITY
grp "3 · Observability wiring"
if on; then
  # 16 seq.txt is read/written by a tool
  grep -rlq 'seq.txt' tools/*.sh tools/*.py 2>/dev/null && ok "seq_txt_is_wired" || no "seq_txt_is_wired" "no tool reads/writes seq.txt (SKILL claims pre-increment)"
  # 17 post-write hook emits an observe event
  [ "$(grep -c observe tools/post-write-hook.sh)" -gt 0 ] && ok "post_write_hook_emits_observe" || no "post_write_hook_emits_observe" "hook emits no observe event ('mechanical logging' unwired)"
  # 18 emitted event types are in the closed vocabulary
  # core closed set + the two enforcement-hook events the SKILL documents (STUB/CONFORMANCE)
  VOCAB="SPAWN PHASE GATE READ WRITE TOOL SEND RECV DECIDE ESCALATE LOOP_START LOOP_ITER LOOP_END STOP CONTEXT COMPLETE ERROR STUB CONFORMANCE"
  extra=""; for e in $(grep -hoE '"event":[[:space:]]*"[A-Z_]+"' tools/*hook*.sh tools/*hook*.py 2>/dev/null | grep -oE '[A-Z_]+"$' | tr -d '"' | sort -u); do echo " $VOCAB " | grep -q " $e " || extra="$extra $e"; done
  [ -z "$extra" ] && ok "observe_event_vocabulary_closed" || no "observe_event_vocabulary_closed" "out-of-vocab:$extra"
  # 19 no stale role labels in dashboard
  [ "$(grep -ciwE 'supervisor|implementor|impl-[0-9]' docs/observatory.html)" = 0 ] && ok "no_stale_role_labels_in_dashboard" || no "no_stale_role_labels_in_dashboard" "stale role labels present"
  # 20 dashboard JS parses
  if command -v node >/dev/null; then
    python3 - >/tmp/_obs.js <<'PY'
import re; s=open('docs/observatory.html').read()
open('/tmp/_obs.js','w').write('\n;\n'.join(re.findall(r'<script(?![^>]*src=)[^>]*>(.*?)</script>',s,flags=re.S)))
PY
    node --check /tmp/_obs.js >/dev/null 2>&1 && ok "dashboard_js_parses" || no "dashboard_js_parses" "syntax error"
  else sk "dashboard_js_parses" "node not installed"; fi
  # 21 generated demo observatory keeps the live poll-since spine
  if [ -f "$DEMO/docs/observatory.html" ]; then
    grep -qE 'api/events\?since|setInterval|lastSeq' "$DEMO/docs/observatory.html" && ok "generated_observatory_is_live_spine" || no "generated_observatory_is_live_spine" "demo observatory is a static snapshot"
  else sk "generated_observatory_is_live_spine" "no demo fixture"; fi
fi

# ───────────────────────────────────────────────────────────── 4. EVAL + TEST THEATER
grp "4 · Evals + Test Theater"
if on; then
  # 22 runner executes a smoke workflow (on a copy, agents off)
  if python3 -c 'import json,sys; d=json.load(open("docs/workflows.json")); sys.exit(0 if d else 1)' 2>/dev/null; then
    R=/tmp/rw-runner-check; rm -rf "$R"; cp -R . "$R" 2>/dev/null
    if (cd "$R" && python3 tools/workflow-runner.py --wf WF-1 --agents off 2>/dev/null | grep -qiE 'PASS|pass'); then ok "runner_executes_smoke"; else no "runner_executes_smoke" "runner did not report PASS"; fi
    rm -rf "$R"
  else sk "runner_executes_smoke" "no workflows.json"; fi
  # 23 workflow node schema (golden on workflow, not node)
  python3 -c "import json;d=json.load(open('docs/workflows.json'));ws=d['workflows'] if isinstance(d,dict) and 'workflows' in d else (list(d.values()) if isinstance(d,dict) else d);w=ws[0];n=w['nodes'][0];need={'id','in','proc','out','view','exec'};assert need<=set(n),need-set(n);assert 'golden' not in n;print('OK')" >/dev/null 2>&1 && ok "workflow_node_schema" || no "workflow_node_schema" "node shape drift (golden on node, or missing keys)"
  # 24 all exec kinds runnable by the runner
  python3 -c "import json;d=json.load(open('docs/workflows.json'));ws=d['workflows'] if isinstance(d,dict) and 'workflows' in d else (list(d.values()) if isinstance(d,dict) else d);ok={'note','file','glob','read_json','cmd','codex','human'};bad=[(n['id'],(n.get('exec') or {}).get('kind')) for w in ws for n in w['nodes'] if (n.get('exec') or {}).get('kind') not in ok];assert not bad,bad;print('OK')" >/dev/null 2>&1 && ok "all_exec_kinds_runnable" || no "all_exec_kinds_runnable" "a node exec.kind the runner can't run"
  # 25 coverage proof present in the demo
  if [ -f "$DEMO/.rapid/COVERAGE.json" ]; then
    python3 -c "import json;c=json.load(open('$DEMO/.rapid/COVERAGE.json'));assert 'untouched_functions' in c;assert c['pass'] is False;print('OK')" >/dev/null 2>&1 && ok "coverage_proof_present" || no "coverage_proof_present" "COVERAGE.json malformed"
  else sk "coverage_proof_present" "no demo fixture"; fi
  # 26 testsuite no-server fallback
  grep -q 'workflows.json' docs/testsuite.html && grep -qE 'catch\(' docs/testsuite.html && ok "testsuite_no_server_fallback" || no "testsuite_no_server_fallback" "no graceful fallback"
  # 27 iframe view src pages exist
  miss=$(python3 -c "import json,os;d=json.load(open('docs/workflows.json'));ws=d['workflows'] if isinstance(d,dict) and 'workflows' in d else (list(d.values()) if isinstance(d,dict) else d);print(' '.join(sorted({v['src'] for w in ws for n in w['nodes'] for v in [n.get('view') or {}] if v.get('src') and not os.path.isfile('docs/'+v['src'])})))" 2>/dev/null)
  [ -z "$miss" ] && ok "iframe_view_pages_exist" || no "iframe_view_pages_exist" "missing:$miss"
fi

# ───────────────────────────────────────────────────────────── 5. DOCS / ATLAS
grp "5 · Documentation / Atlas coherence"
if on; then
  # 08 atlas regenerates with no drift (on a copy, leave repo clean)
  A=/tmp/rw-atlas-check; rm -rf "$A"; cp -R . "$A" 2>/dev/null
  (cd "$A" && python3 tools/atlas-skills-gen.py >/dev/null 2>&1; git checkout docs.json >/dev/null 2>&1)
  drift=$(cd "$A" && git status --porcelain docs/atlas-v2/ 2>/dev/null)
  [ -z "$drift" ] && ok "atlas_generator_no_drift" || no "atlas_generator_no_drift" "stale: $(echo $drift | sed 's/ M docs.atlas-v2.//g' | head -c70)"
  rm -rf "$A"
  # 28 CODEBASE eight skills
  N=$(ls -1 skills/ | wc -l | tr -d ' '); grep -q 'eight skills' CODEBASE.md && grep -q 'observe/SKILL.md' CODEBASE.md && grep -q 'test-theater/SKILL.md' CODEBASE.md && [ "$N" = 8 ] && ok "codebase_eight_skills" || no "codebase_eight_skills" "CODEBASE/skills mismatch (ls=$N)"
  # 29 README eight skills + all symlinks listed
  rm=""; grep -qiE 'eight skills|8 skills' README.md || rm="count"; for s in rapid-workflow decision docs workflow expert-panel refine observe test-theater; do grep -q "skills/$s" README.md || rm="$rm $s"; done
  [ -z "$rm" ] && ok "readme_eight_skills_and_symlinks" || no "readme_eight_skills_and_symlinks" "missing:$rm"
  # 30 architecture D0..D32 contiguous
  SEQ=$(grep -oE '\bD[0-9]+\b' docs/architecture.html | sed 's/D//' | awk '$1<=32' | sort -n -u | tr '\n' ' ')
  [ "$SEQ" = "$(seq 0 32 | tr '\n' ' ')" ] && ok "architecture_D0_D32_contiguous" || no "architecture_D0_D32_contiguous" "gaps in D0..D32"
  # 31 no stale build-team refs repo-wide
  st=$(grep -rniwE 'supervisor|implementor|3-terminal' skills/ docs/ CODEBASE.md README.md 2>/dev/null | grep -viE '/CHANGELOG\.md|cost\.html|doc-model-brainstorm|ecc-analysis\.html|selftest' )
  [ -z "$st" ] && ok "no_stale_build_team_refs" || no "no_stale_build_team_refs" "$(echo "$st" | wc -l | tr -d ' ') stale refs"
fi

# ───────────────────────────────────────────────────────────── 6. DYNAMIC BUILD
grp "6 · Dynamic self-build proof"
if on; then
  # 35 atlas-init scaffolds testsuite + wires the skills
  if bash -n tools/atlas-init.sh 2>/dev/null; then
    AF=/tmp/rw-af; rm -rf "$AF"; mkdir -p "$AF"; bash tools/atlas-init.sh "$AF" >/dev/null 2>&1
    if [ -f "$AF/docs/testsuite.html" ] && python3 -c "import json;r=json.load(open('$AF/docs/regen.json'));assert 'test-theater' in json.dumps(r);assert 'observe' in json.dumps(r)" 2>/dev/null; then ok "atlas_init_scaffold_and_wiring"; else no "atlas_init_scaffold_and_wiring" "testsuite/skills not scaffolded"; fi
    rm -rf "$AF"
  else no "atlas_init_scaffold_and_wiring" "bash -n failed"; fi
  # 36 skills product-agnostic
  grep -Eiq 'shopfast|acme|petstore|todomvc' skills/observe/SKILL.md skills/test-theater/SKILL.md && no "skills_product_agnostic" "product name leaked" || ok "skills_product_agnostic"
  # 37 skills symlinked
  [ "$(readlink ~/.claude/skills/observe 2>/dev/null)" = "$PWD/skills/observe" ] && [ "$(readlink ~/.claude/skills/test-theater 2>/dev/null)" = "$PWD/skills/test-theater" ] && ok "skills_symlinked" || no "skills_symlinked" "not symlinked into ~/.claude/skills"
  # 38 spine compiles
  python3 -m py_compile tools/observe-server.py tools/workflow-runner.py 2>/dev/null && ok "spine_compiles" || no "spine_compiles" "observe-server/workflow-runner won't compile"
  # 33/34 derivation proofs (demo-dependent)
  if [ -f "$DEMO/build-test-theater.py" ]; then
    N=/tmp/rds-neg; rm -rf "$N"; cp -R "$DEMO" "$N"
    printf '\nexport function zzSelftest(){return 1;}\n' >> "$N/src/catalog.js"
    (cd "$N" && python3 build-test-theater.py >/dev/null 2>&1)
    python3 -c "import json;print('zzSelftest' in json.load(open('$N/.rapid/COVERAGE.json'))['untouched_functions'])" 2>/dev/null | grep -q True && ok "derivation_tracks_function_inventory" || no "derivation_tracks_function_inventory" "new fn not surfaced as a gap"
    rm -rf "$N"
    R=/tmp/rds-rost; rm -rf "$R"; cp -R "$DEMO" "$R"; printf '# notifier\n' > "$R/04-spec/agents/notifier.md"
    (cd "$R" && python3 build-observe.py >/dev/null 2>&1)
    [ "$(grep -c notifier "$R/docs/observatory.html" 2>/dev/null || echo 0)" -ge 1 ] && ok "derivation_tracks_agent_roster" || no "derivation_tracks_agent_roster" "new agent didn't add a lane"
    rm -rf "$R"
  else sk "derivation_tracks_function_inventory" "no demo fixture"; sk "derivation_tracks_agent_roster" "no demo fixture"; fi
fi

# ───────────────────────────────────────────────────────────── SUMMARY
printf "\n${CB}─── selftest summary ───${C0}\n"
printf "  ${CG}%d passed${C0} · ${CR}%d failed${C0} · ${CY}%d skipped${C0}  (of %d checks)\n" "$PASS" "$FAIL" "$SKIP" "$((PASS+FAIL+SKIP))"
if [ "$FAIL" -gt 0 ]; then printf "  failing: %s\n" "${FAILED[*]}"; fi
[ "$FAIL" -eq 0 ]
